**

!package.json
!pnpm-lock.yaml
!pnpm-workspace.yaml
!apps/
!apps/legislation/
!apps/legislation/**
!packages/
!packages/**

**/.env
**/.env.*
**/.git
**/.turbo
**/coverage
!apps/legislation/src/coverage/
!apps/legislation/src/coverage/**
**/dist
**/node_modules
