**

!package.json
!pnpm-lock.yaml
!pnpm-workspace.yaml
!apps/
!apps/legislation/
!apps/legislation/**
!packages/
!packages/oxlint-config/
!packages/oxlint-config/**
!packages/typescript-config/
!packages/typescript-config/**

**/.env
**/.env.*
**/.git
**/.next
**/.turbo
**/coverage
!apps/legislation/src/coverage/
!apps/legislation/src/coverage/**
**/dist
**/node_modules
**/*.tsbuildinfo
