**

!package.json
!pnpm-lock.yaml
!pnpm-workspace.yaml
!apps/
!apps/legislation-web/
!apps/legislation-web/**
!packages/
!packages/legislation-core/
!packages/legislation-core/**
!packages/oxlint-config/
!packages/oxlint-config/**
!packages/typescript-config/
!packages/typescript-config/**

**/.env
**/.env.*
**/.git
**/.next
**/.turbo
**/coverage
!apps/legislation-web/src/modules/legislation/coverage/
!apps/legislation-web/src/modules/legislation/coverage/**
**/dist
**/node_modules
**/*.tsbuildinfo
