**

!.npmrc
!package.json
!pnpm-lock.yaml
!pnpm-workspace.yaml
!apps/
!apps/legislation/
!apps/legislation/**
!apps/legislation-web/
!apps/legislation-web/**
!packages/
!packages/**

**/.env
**/.env.*
**/.git
**/.next
**/.turbo
**/coverage
!apps/legislation/src/coverage/
!apps/legislation/src/coverage/**
**/node_modules
**/*.tsbuildinfo
