ALTER TABLE "legislation"."bill_documents" ADD COLUMN "ocr_status" text;--> statement-breakpoint
ALTER TABLE "legislation"."bill_documents" ADD COLUMN "ocr_provider" text;--> statement-breakpoint
ALTER TABLE "legislation"."bill_documents" ADD COLUMN "ocr_completed_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "legislation"."bill_documents" ADD COLUMN "ocr_page_count" integer;--> statement-breakpoint
ALTER TABLE "legislation"."document_sections" ADD COLUMN "page_start" integer;--> statement-breakpoint
ALTER TABLE "legislation"."document_sections" ADD COLUMN "page_end" integer;--> statement-breakpoint
ALTER TABLE "legislation"."bill_documents" ADD CONSTRAINT "bill_documents_ocr_status_check" CHECK ("legislation"."bill_documents"."ocr_status" is null or "legislation"."bill_documents"."ocr_status" in ('not-required', 'pending', 'processing', 'processed', 'failed', 'unsupported'));--> statement-breakpoint
ALTER TABLE "legislation"."bill_documents" ADD CONSTRAINT "bill_documents_ocr_provider_check" CHECK ("legislation"."bill_documents"."ocr_provider" is null or length(btrim("legislation"."bill_documents"."ocr_provider")) > 0);--> statement-breakpoint
ALTER TABLE "legislation"."bill_documents" ADD CONSTRAINT "bill_documents_ocr_page_count_check" CHECK ("legislation"."bill_documents"."ocr_page_count" is null or "legislation"."bill_documents"."ocr_page_count" > 0);--> statement-breakpoint
ALTER TABLE "legislation"."bill_documents" ADD CONSTRAINT "bill_documents_ocr_success_check" CHECK ("legislation"."bill_documents"."ocr_status" <> 'processed' or ("legislation"."bill_documents"."ocr_provider" is not null and length(btrim("legislation"."bill_documents"."ocr_provider")) > 0 and "legislation"."bill_documents"."ocr_completed_at" is not null));--> statement-breakpoint
ALTER TABLE "legislation"."bill_documents" ADD CONSTRAINT "bill_documents_ocr_metadata_status_check" CHECK (("legislation"."bill_documents"."ocr_provider" is null and "legislation"."bill_documents"."ocr_completed_at" is null and "legislation"."bill_documents"."ocr_page_count" is null) or "legislation"."bill_documents"."ocr_status" is not distinct from 'processed');--> statement-breakpoint
ALTER TABLE "legislation"."document_sections" ADD CONSTRAINT "document_sections_page_range_check" CHECK (("legislation"."document_sections"."page_start" is null and "legislation"."document_sections"."page_end" is null) or ("legislation"."document_sections"."page_start" > 0 and "legislation"."document_sections"."page_end" >= "legislation"."document_sections"."page_start"));
