import { execFile, spawn } from "node:child_process"
import { fileURLToPath } from "node:url"
import { promisify } from "node:util"
import pg from "pg"
import { afterAll, beforeAll, describe, expect, it } from "vitest"
import { createBulkCopyEngine } from "./copy-engine.js"
import { type ExternalHook } from "./external-hook.js"
import { createDeterministicFixtureHook, createPassageRebuildHook, createPostgresLockHook } from "./platform-hooks.js"
import { createPostgresRefreshStore } from "./postgres-store.js"
import { refreshStaging, type RefreshEndpoints } from "./refresh.js"

const sourceEndpoint = process.env.LEGISLATION_REFRESH_TEST_SOURCE_DATABASE_URL
const targetEndpoint = process.env.LEGISLATION_REFRESH_TEST_TARGET_DATABASE_URL
const passageSearchEndpoint = process.env.LEGISLATION_REFRESH_TEST_PASSAGE_SEARCH_DATABASE_URL
const postgresContainer = process.env.LEGISLATION_REFRESH_TEST_POSTGRES_CONTAINER
const enabled = [sourceEndpoint, targetEndpoint, passageSearchEndpoint, postgresContainer].every(Boolean)
const execFileAsync = promisify(execFile)

function assertDisposableEndpoint(endpoint: string, expectedDatabase: string) {
  const url = new URL(endpoint)
  if (
    !["127.0.0.1", "localhost"].includes(url.hostname) ||
    decodeURIComponent(url.pathname.slice(1)) !== expectedDatabase
  ) {
    throw new Error(`Refresh integration endpoint must target local disposable ${expectedDatabase}`)
  }
}

async function resetDatabase(endpoint: string) {
  const client = new pg.Client({ connectionString: endpoint })
  await client.connect()
  await client.query("drop schema if exists legislation cascade; drop schema if exists legislation_migrations cascade")
  await client.end()
  const migration =
    process.platform === "win32"
      ? {
          command: process.env.ComSpec ?? "cmd.exe",
          arguments_: ["/d", "/s", "/c", "pnpm --filter @repo/legislation-core db:migrate"]
        }
      : { command: "pnpm", arguments_: ["--filter", "@repo/legislation-core", "db:migrate"] }
  await execFileAsync(migration.command, migration.arguments_, {
    cwd: fileURLToPath(new URL("../../../../../", import.meta.url)),
    env: { ...process.env, DATABASE_URL: endpoint }
  })
  const migrated = new pg.Client({ connectionString: endpoint })
  await migrated.connect()
  await migrated.query(
    "alter table legislation.jurisdictions add column refresh_copy_id bigint generated by default as identity"
  )
  await migrated.query("alter table legislation.jurisdictions add column refresh_embedding vector(3)")
  await migrated.end()
}

function dockerPostgresSpawn(command: string, arguments_: readonly string[], environment: NodeJS.ProcessEnv) {
  const forwarded = ["PGAPPNAME", "PGDATABASE", "PGUSER", "PGPASSWORD", "PGSSLMODE", "PGOPTIONS"]
    .filter((name) => environment[name] !== undefined)
    .flatMap((name) => ["--env", `${name}=${environment[name]}`])
  return spawn(
    "docker",
    [
      "exec",
      "-i",
      ...forwarded,
      "--env",
      "PGHOST=127.0.0.1",
      "--env",
      "PGPORT=5432",
      postgresContainer!,
      command,
      ...arguments_
    ],
    { stdio: ["pipe", "pipe", "pipe"], windowsHide: true }
  )
}

async function query(endpoint: string, text: string, values: unknown[] = []) {
  const client = new pg.Client({ connectionString: endpoint })
  await client.connect()
  try {
    return await client.query(text, values)
  } finally {
    await client.end()
  }
}

async function seedSource() {
  await query(
    sourceEndpoint!,
    `insert into legislation.jurisdictions
      (id,name,classification,country_code,source_url,refresh_embedding)
     values ('jurisdiction:refresh:test','Refresh Test','country','US','https://example.test/jurisdiction','[1,2,3]')
     returning refresh_copy_id`
  )
  await query(
    sourceEndpoint!,
    `insert into legislation.legislative_sessions(id,jurisdiction_id,identifier,name)
     values ('session:refresh:test','jurisdiction:refresh:test','refresh','Refresh session');
     insert into legislation.bills
       (id,jurisdiction_id,session_id,identifier,title,classification,status,source_url)
     values
       ('bill:refresh:test:hr:1','jurisdiction:refresh:test','session:refresh:test','H.R. 1',
        'Refresh fixture bill',array['bill'],'introduced','https://example.test/bill');
     insert into legislation.bill_documents
       (id,bill_id,classification,version_code,title,source_url,processing_status)
     values
       ('document:refresh:test','bill:refresh:test:hr:1','bill-text','introduced',
        'Refresh fixture text','https://example.test/document','processed');
     insert into legislation.document_sections
       (id,document_id,ordinal,text,content_hash,source_start_offset,source_end_offset)
     values
       ('section:refresh:test','document:refresh:test',1,'Deterministic refresh passage',
        repeat('a',64),0,29);
     insert into legislation.webhooks
       (id,owner_user_id,name,url,event_types,secret_last_four)
     values
       ('webhook:source-private','source-user','Source private','https://example.test/source',
        array['bill.updated'],'0000');
     insert into legislation.research_result_snapshots(id,session_key,snapshot,expires_at)
     values
       ('00000000-0000-0000-0000-000000000001','00000000-0000-0000-0000-000000000002',
        '{"private":"source"}',now()+interval '1 day')`
  )
}

describe.skipIf(!enabled)("staging refresh with disposable PostgreSQL 18", () => {
  const endpoints: RefreshEndpoints = {
    sourcePrimary: sourceEndpoint!,
    targetPrimary: targetEndpoint!,
    targetPassageSearch: passageSearchEndpoint!,
    targetWeb: "https://web.staging.invalid",
    targetMcp: "https://mcp.staging.invalid"
  }
  const maintenance: boolean[] = []

  beforeAll(async () => {
    assertDisposableEndpoint(sourceEndpoint!, "legislation_refresh_source_test")
    assertDisposableEndpoint(targetEndpoint!, "legislation_refresh_target_test")
    assertDisposableEndpoint(passageSearchEndpoint!, "legislation_passage_search_destructive_test")
    await Promise.all([resetDatabase(sourceEndpoint!), resetDatabase(targetEndpoint!)])
    await query(passageSearchEndpoint!, "truncate table legislation.document_sections cascade")
    await seedSource()
    await query(
      targetEndpoint!,
      `insert into legislation.jurisdictions
        (id,name,classification,country_code,source_url,refresh_embedding)
       values ('jurisdiction:stale','Stale','country','CA','https://example.test/stale','[0,0,0]');
       insert into legislation.webhooks
        (id,owner_user_id,name,url,event_types,secret_last_four)
       values ('webhook:staging-owned','staging-user','Staging owned',
        'https://staging.invalid/webhook',array['bill.updated'],'1111')`
    )
  }, 600_000)

  afterAll(async () => {
    await Promise.allSettled([
      query(
        sourceEndpoint!,
        "drop schema if exists legislation cascade; drop schema if exists legislation_migrations cascade"
      ),
      query(
        targetEndpoint!,
        "drop schema if exists legislation cascade; drop schema if exists legislation_migrations cascade"
      ),
      query(passageSearchEndpoint!, "truncate table legislation.document_sections")
    ])
  })

  it("runs bulk copy, sanitization, fixture seeding, rebuild, and validation", async () => {
    const rebuildHook = createPassageRebuildHook(targetEndpoint!, passageSearchEndpoint!)
    const fixtureHook = createDeterministicFixtureHook(targetEndpoint!)
    const smokeHook: ExternalHook = async () => "true,true"
    const source = createPostgresRefreshStore({
      endpoint: sourceEndpoint!,
      rebuildHook,
      fixtureHook,
      smokeHook
    })
    const target = createPostgresRefreshStore({
      endpoint: targetEndpoint!,
      sourceEndpoint: sourceEndpoint!,
      passageSearchEndpoint: passageSearchEndpoint!,
      rebuildHook,
      fixtureHook,
      smokeHook
    })
    try {
      const result = await refreshStaging({
        endpoints,
        source,
        target,
        copyEngine: createBulkCopyEngine(dockerPostgresSpawn),
        hooks: {
          acquireLock: createPostgresLockHook(targetEndpoint!),
          async assertMigrationLeaseAvailable() {},
          async setMaintenance(unavailable) {
            maintenance.push(unavailable)
          },
          async alert() {
            throw new Error("Success must not alert")
          }
        }
      })
      expect(result.receipt.engine).toBe("bulk")
      expect(Object.values(result.validation).every(Boolean)).toBe(true)
    } finally {
      await Promise.allSettled([source.close(), target.close()])
    }

    const copied = await query(
      targetEndpoint!,
      `select id,refresh_copy_id,refresh_embedding::text embedding
       from legislation.jurisdictions order by id`
    )
    expect(copied.rows).toEqual([{ id: "jurisdiction:refresh:test", refresh_copy_id: "1", embedding: "[1,2,3]" }])
    expect(
      (await query(targetEndpoint!, "select count(*)::int count from legislation.research_result_snapshots")).rows[0]
    ).toEqual({ count: 0 })
    expect((await query(targetEndpoint!, "select id from legislation.webhooks order by id")).rows).toEqual([
      { id: "webhook:staging-owned" },
      { id: "webhook:staging-refresh-fixture" }
    ])
    expect(
      (
        await query(
          passageSearchEndpoint!,
          `select id from legislation.document_sections
           where id @@@ pdb.parse('body:Deterministic',lenient=>false,conjunction_mode=>true)`
        )
      ).rows
    ).toEqual([{ id: "section:refresh:test" }])
    expect(maintenance).toEqual([true, false])
    const release = await createPostgresLockHook(targetEndpoint!)()
    await release()
  }, 600_000)

  it("releases resources and retains maintenance on validation failure", async () => {
    maintenance.length = 0
    const alerts: string[] = []
    const rebuildHook = createPassageRebuildHook(targetEndpoint!, passageSearchEndpoint!)
    const fixtureHook = createDeterministicFixtureHook(targetEndpoint!)
    const smokeHook: ExternalHook = async () => "true,false"
    const source = createPostgresRefreshStore({
      endpoint: sourceEndpoint!,
      rebuildHook,
      fixtureHook,
      smokeHook
    })
    const target = createPostgresRefreshStore({
      endpoint: targetEndpoint!,
      sourceEndpoint: sourceEndpoint!,
      passageSearchEndpoint: passageSearchEndpoint!,
      rebuildHook,
      fixtureHook,
      smokeHook
    })
    try {
      await expect(
        refreshStaging({
          endpoints,
          source,
          target,
          copyEngine: createBulkCopyEngine(dockerPostgresSpawn),
          hooks: {
            acquireLock: createPostgresLockHook(targetEndpoint!),
            async assertMigrationLeaseAvailable() {},
            async setMaintenance(unavailable) {
              maintenance.push(unavailable)
            },
            async alert(message) {
              alerts.push(message)
            }
          }
        })
      ).rejects.toThrow("mcpSmoke")
      expect(await source.beginSourceSnapshot()).toMatch(/^[0-9A-Fa-f]+-[0-9A-Fa-f]+-[0-9]+$/)
      await source.endSourceSnapshot()
    } finally {
      await Promise.allSettled([source.close(), target.close()])
    }
    expect(maintenance).toEqual([true, true])
    expect(alerts).toHaveLength(1)
    const release = await createPostgresLockHook(targetEndpoint!)()
    await release()
  }, 600_000)
})
