// Generated by D:\tutor\scripts\export_completed_atomic_graph.py.
// Kept separate so Guided Story does not parse the full Explore graph.
export const completedGraphMetadata = {
  campaignKey: "universal-math-atomic-subgraphs-v1",
  outcomeRelationshipRunKey: "universal-math-outcome-prerequisites-v2",
  generatedAt: "2026-07-28T04:35:22.915102Z",
  completedOutcomeCount: 346,
  outcomeProposalReferenceCount: 638,
  collapsedOutcomeCount: 292,
  atomicNodeCount: 1915,
  atomicProposalReferenceCount: 4004,
  collapsedProposalCount: 2108,
  atomicEdgeCount: 5469,
  outcomeHardEdgeCount: 49,
  outcomeSupportEdgeCount: 439,
  outcomeRelationshipEdgeCount: 488,
  edgeCount: 5957,
  componentCount: 12,
  learningActivityCount: 205,
  learningResourceCount: 205
} as const
